listener 8884
protocol mqtt

cafile /etc/ncms/pki/ca.crt
certfile /etc/ncms/pki/mosquitto-ncms.crt
keyfile /etc/ncms/pki/mosquitto-ncms.key

require_certificate true
use_identity_as_username true
allow_anonymous false

acl_file /etc/mosquitto-ncms/acl

persistence true
persistence_location /var/lib/mosquitto-ncms/

log_dest file /var/log/mosquitto/mosquitto-ncms.log
log_type error
log_type warning
log_type notice
log_type information
