// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NCMS.IoT.DeviceManagement.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NCMS.IoT.DeviceManagement.Migrations
{
    [DbContext(typeof(DeviceManagementDbContext))]
    [Migration("20260625141132_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NCMS.IoT.DeviceManagement.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ActivatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AgentVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("FirmwareVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("HardwareInventoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("HardwareModel")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsOnline")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("HardwareInventoryId")
                        .IsUnique();

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("NCMS.IoT.DeviceManagement.Entities.DeviceCertificate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CertificatePem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Thumbprint")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("Thumbprint")
                        .IsUnique()
                        .HasDatabaseName("ix_device_certificates_thumbprint");

                    b.HasIndex("DeviceId", "IsActive")
                        .HasDatabaseName("ix_device_certificates_device_id_is_active");

                    b.ToTable("device_certificates", (string)null);
                });

            modelBuilder.Entity("NCMS.IoT.DeviceManagement.Entities.DeviceEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Severity")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "EventType")
                        .HasDatabaseName("ix_device_events_device_id_event_type");

                    b.HasIndex("DeviceId", "Timestamp")
                        .HasDatabaseName("ix_device_events_device_id_timestamp");

                    b.ToTable("device_events", (string)null);
                });

            modelBuilder.Entity("NCMS.IoT.DeviceManagement.Entities.FirmwareAuditRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DetailsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EntityType", "EntityId", "Timestamp");

                    b.ToTable("FirmwareAuditRecords", "firmware");
                });

            modelBuilder.Entity("NCMS.IoT.DeviceManagement.Entities.FirmwareCampaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("FirmwarePackageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RolloutConfigJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("RolloutStrategy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TargetSpecJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<decimal>("UpgradeDurationHours")
                        .HasColumnType("numeric(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("FirmwarePackageId");

                    b.ToTable("FirmwareCampaigns", "firmware");
                });

            modelBuilder.Entity("NCMS.IoT.DeviceManagement.Entities.FirmwareDeploymentJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DispatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("OriginalFirmwareVersion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("Stage")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId", "Status");

                    b.HasIndex("DeviceId", "Status");

                    b.ToTable("FirmwareDeploymentJobs", "firmware");
                });

            modelBuilder.Entity("NCMS.IoT.DeviceManagement.Entities.FirmwareHardwareVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChipsetId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DeviceTypeCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("MaxFirmwareSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PcbRevision")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("FirmwareHardwareVariants", "firmware");
                });

            modelBuilder.Entity("NCMS.IoT.DeviceManagement.Entities.FirmwarePackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BinaryChecksum")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeviceTypeCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DigitalSignature")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Md5Checksum")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("MinRequiredFirmwareVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReleaseNotes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceTypeCode", "Version")
                        .HasDatabaseName("ix_firmware_packages_devicetypecode_version");

                    b.HasIndex("Name", "Version", "Type")
                        .IsUnique()
                        .HasDatabaseName("ix_firmware_packages_name_version_type");

                    b.ToTable("FirmwarePackages", "firmware");
                });

            modelBuilder.Entity("NCMS.IoT.DeviceManagement.Entities.FirmwarePackageVariant", b =>
                {
                    b.Property<Guid>("PackageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VariantId")
                        .HasColumnType("uuid");

                    b.HasKey("PackageId", "VariantId");

                    b.HasIndex("VariantId");

                    b.ToTable("FirmwarePackageVariants", "firmware");
                });

            modelBuilder.Entity("NCMS.IoT.DeviceManagement.Entities.FirmwareProduct", b =>
                {
                    b.Property<Guid>("FirmwareId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.HasKey("FirmwareId", "ProductId");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_firmware_products_product_id");

                    b.ToTable("firmware_products", "firmware");
                });

            modelBuilder.Entity("NCMS.IoT.DeviceManagement.Entities.HardwareInventory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsProvisioned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("MacAddress")
                        .IsUnique()
                        .HasDatabaseName("ix_hardware_inventory_mac_address");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_hardware_inventory_product_id");

                    b.HasIndex("SerialNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_hardware_inventory_serial_number");

                    b.ToTable("hardware_inventory", (string)null);
                });

            modelBuilder.Entity("NCMS.IoT.DeviceManagement.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ProductTypeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("SupportsCommands")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("SupportsConfiguration")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("SupportsFirmwareUpgrade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("SupportsRealtimeLogs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("SupportsRemoteConfiguration")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("SupportsTelemetry")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("SupportsFirmwareUpgrade")
                        .HasDatabaseName("ix_products_supports_firmware_upgrade")
                        .HasFilter("\"SupportsFirmwareUpgrade\" = TRUE");

                    b.HasIndex("ProductTypeId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_products_type_name")
                        .HasFilter("\"IsDeleted\" = FALSE");

                    b.ToTable("products", "products");
                });

            modelBuilder.Entity("NCMS.IoT.DeviceManagement.Entities.ProductCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_product_categories_name")
                        .HasFilter("\"IsDeleted\" = FALSE");

                    b.ToTable("product_categories", "products");
                });

            modelBuilder.Entity("NCMS.IoT.DeviceManagement.Entities.ProductType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ProductCategoryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductCategoryId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_product_types_category_name")
                        .HasFilter("\"IsDeleted\" = FALSE");

                    b.ToTable("product_types", "products");
                });

            modelBuilder.Entity("NCMS.IoT.DeviceManagement.Entities.TelemetryRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<byte>("QosLevel")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "Timestamp")
                        .HasDatabaseName("ix_telemetry_records_device_id_timestamp");

                    b.ToTable("telemetry_records", (string)null);
                });

            modelBuilder.Entity("NCMS.IoT.DeviceManagement.Entities.UpgradeTask", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FirmwareId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<TimeSpan?>("UpgradeTimeout")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("FirmwareId")
                        .HasDatabaseName("ix_upgrade_tasks_firmware_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_upgrade_tasks_pending")
                        .HasFilter("\"Status\" = 0");

                    b.ToTable("upgrade_tasks", "firmware");
                });

            modelBuilder.Entity("NCMS.IoT.DeviceManagement.Entities.UpgradeTaskDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("PreviousFirmwareVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TargetFirmwareVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UpgradeTaskId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "Status")
                        .HasDatabaseName("ix_upgrade_task_devices_device_status");

                    b.HasIndex("UpgradeTaskId", "DeviceId")
                        .IsUnique()
                        .HasDatabaseName("ix_upgrade_task_devices_task_device");

                    b.HasIndex("UpgradeTaskId", "Status")
                        .HasDatabaseName("ix_upgrade_task_devices_task_active")
                        .HasFilter("\"Status\" IN (0, 1)");

                    b.ToTable("upgrade_task_devices", "firmware");
                });

            modelBuilder.Entity("NCMS.IoT.DeviceManagement.Entities.Device", b =>
                {
                    b.HasOne("NCMS.IoT.DeviceManagement.Entities.HardwareInventory", "HardwareInventory")
                        .WithOne("Device")
                        .HasForeignKey("NCMS.IoT.DeviceManagement.Entities.Device", "HardwareInventoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HardwareInventory");
                });

            modelBuilder.Entity("NCMS.IoT.DeviceManagement.Entities.DeviceCertificate", b =>
                {
                    b.HasOne("NCMS.IoT.DeviceManagement.Entities.Device", "Device")
                        .WithMany("Certificates")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("NCMS.IoT.DeviceManagement.Entities.DeviceEvent", b =>
                {
                    b.HasOne("NCMS.IoT.DeviceManagement.Entities.Device", "Device")
                        .WithMany("Events")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("NCMS.IoT.DeviceManagement.Entities.FirmwareCampaign", b =>
                {
                    b.HasOne("NCMS.IoT.DeviceManagement.Entities.FirmwarePackage", "Package")
                        .WithMany("Campaigns")
                        .HasForeignKey("FirmwarePackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Package");
                });

            modelBuilder.Entity("NCMS.IoT.DeviceManagement.Entities.FirmwareDeploymentJob", b =>
                {
                    b.HasOne("NCMS.IoT.DeviceManagement.Entities.FirmwareCampaign", "Campaign")
                        .WithMany("Jobs")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("NCMS.IoT.DeviceManagement.Entities.FirmwarePackageVariant", b =>
                {
                    b.HasOne("NCMS.IoT.DeviceManagement.Entities.FirmwarePackage", "Package")
                        .WithMany("CompatibleVariants")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NCMS.IoT.DeviceManagement.Entities.FirmwareHardwareVariant", "Variant")
                        .WithMany("Packages")
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("NCMS.IoT.DeviceManagement.Entities.FirmwareProduct", b =>
                {
                    b.HasOne("NCMS.IoT.DeviceManagement.Entities.FirmwarePackage", "Firmware")
                        .WithMany("FirmwareProducts")
                        .HasForeignKey("FirmwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NCMS.IoT.DeviceManagement.Entities.Product", "Product")
                        .WithMany("FirmwareProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Firmware");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("NCMS.IoT.DeviceManagement.Entities.HardwareInventory", b =>
                {
                    b.HasOne("NCMS.IoT.DeviceManagement.Entities.Product", "Product")
                        .WithMany("HardwareInventories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("NCMS.IoT.DeviceManagement.Entities.Product", b =>
                {
                    b.HasOne("NCMS.IoT.DeviceManagement.Entities.ProductType", "ProductType")
                        .WithMany("Products")
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("NCMS.IoT.DeviceManagement.Entities.ProductType", b =>
                {
                    b.HasOne("NCMS.IoT.DeviceManagement.Entities.ProductCategory", "ProductCategory")
                        .WithMany("ProductTypes")
                        .HasForeignKey("ProductCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductCategory");
                });

            modelBuilder.Entity("NCMS.IoT.DeviceManagement.Entities.TelemetryRecord", b =>
                {
                    b.HasOne("NCMS.IoT.DeviceManagement.Entities.Device", "Device")
                        .WithMany("TelemetryRecords")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("NCMS.IoT.DeviceManagement.Entities.UpgradeTask", b =>
                {
                    b.HasOne("NCMS.IoT.DeviceManagement.Entities.FirmwarePackage", "Firmware")
                        .WithMany("UpgradeTasks")
                        .HasForeignKey("FirmwareId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Firmware");
                });

            modelBuilder.Entity("NCMS.IoT.DeviceManagement.Entities.UpgradeTaskDevice", b =>
                {
                    b.HasOne("NCMS.IoT.DeviceManagement.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NCMS.IoT.DeviceManagement.Entities.UpgradeTask", "UpgradeTask")
                        .WithMany("Devices")
                        .HasForeignKey("UpgradeTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("UpgradeTask");
                });

            modelBuilder.Entity("NCMS.IoT.DeviceManagement.Entities.Device", b =>
                {
                    b.Navigation("Certificates");

                    b.Navigation("Events");

                    b.Navigation("TelemetryRecords");
                });

            modelBuilder.Entity("NCMS.IoT.DeviceManagement.Entities.FirmwareCampaign", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("NCMS.IoT.DeviceManagement.Entities.FirmwareHardwareVariant", b =>
                {
                    b.Navigation("Packages");
                });

            modelBuilder.Entity("NCMS.IoT.DeviceManagement.Entities.FirmwarePackage", b =>
                {
                    b.Navigation("Campaigns");

                    b.Navigation("CompatibleVariants");

                    b.Navigation("FirmwareProducts");

                    b.Navigation("UpgradeTasks");
                });

            modelBuilder.Entity("NCMS.IoT.DeviceManagement.Entities.HardwareInventory", b =>
                {
                    b.Navigation("Device");
                });

            modelBuilder.Entity("NCMS.IoT.DeviceManagement.Entities.Product", b =>
                {
                    b.Navigation("FirmwareProducts");

                    b.Navigation("HardwareInventories");
                });

            modelBuilder.Entity("NCMS.IoT.DeviceManagement.Entities.ProductCategory", b =>
                {
                    b.Navigation("ProductTypes");
                });

            modelBuilder.Entity("NCMS.IoT.DeviceManagement.Entities.ProductType", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("NCMS.IoT.DeviceManagement.Entities.UpgradeTask", b =>
                {
                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
