#!/bin/sh /etc/rc.common

START=99
STOP=10

USE_PROCD=1

CONFIGURATION=ncms-config

start_service() {
    config_load "${CONFIGURATION}"
    procd_open_instance
    procd_set_param command /usr/bin/NCMS
    procd_set_param respawn
    procd_set_param file /etc/config/ncms-config
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance

#    ubus wait_for gpio
}

stop_service() {
    killall NCMS 2>/dev/null
}